# Generated by Django 4.0 on 2021-12-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_category_slug_alter_news_slug_alter_tag_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
            ],
            options={
                'verbose_name': 'IPAddress',
                'verbose_name_plural': 'IPAddresses',
            },
        ),
    ]
