# Generated by Django 4.0 on 2021-12-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_remove_comment_news_comment_news_alter_comment_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='hits',
            field=models.ManyToManyField(blank=True, to='news.IPAddress', verbose_name='IP Addresses'),
        ),
    ]
